project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /core/components/minishop2/lexicon/en/*.inc.php
    translation: /core/components/minishop2/lexicon/%two_letters_code%/%original_file_name%
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
